/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 05/12/2024 15:43:17
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            24000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     160000000
#define MX_HCLKFreq_Value                       160000000
#define MX_FCLKCortexFreq_Value                 160000000
#define MX_CortexFreq_Value                     160000000
#define MX_AHBFreq_Value                        160000000
#define MX_APB1Freq_Value                       160000000
#define MX_APB2Freq_Value                       160000000
#define MX_APB1TimFreq_Value                    160000000
#define MX_APB2TimFreq_Value                    160000000
#define MX_ADC12Freq_Value                      20000000
#define MX_LPUART1Freq_Value                    160000000
#define MX_I2C1Freq_Value                       160000000
#define MX_I2SFreq_Value                        160000000
#define MX_USART1Freq_Value                     160000000
#define MX_USART2Freq_Value                     160000000
#define MX_USART3Freq_Value                     160000000
#define MX_FDCANFreq_Value                      160000000
#define MX_LPTIM1Freq_Value                     160000000
#define MX_QSPIFreq_Value                       80000000
#define MX_SAI1Freq_Value                       160000000
#define MX_PWRFreq_Value                        160000000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        48000000
#define MX_WatchDogFreq_Value                   32000
#define MX_CECFreq_Value                        4000000
#define MX_HRTIM1Freq_Value                     160000000
#define MX_MCO1PinFreq_Value                    16000000

/*-------------------------------- ADC1       --------------------------------*/

#define MX_ADC1                                 1

/* GPIO Configuration */

/* Pin PA2 */
#define MX_ADC1_IN3_Pin                         PA2
#define MX_ADC1_IN3_GPIOx                       GPIOA
#define MX_ADC1_IN3_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN3_GPIO_Pin                    GPIO_PIN_2
#define MX_ADC1_IN3_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PA1 */
#define MX_ADC1_IN2_Pin                         PA1
#define MX_ADC1_IN2_GPIOx                       GPIOA
#define MX_ADC1_IN2_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN2_GPIO_Pin                    GPIO_PIN_1
#define MX_ADC1_IN2_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PA0 */
#define MX_ADC1_IN1_Pin                         PA0
#define MX_ADC1_IN1_GPIOx                       GPIOA
#define MX_ADC1_IN1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN1_GPIO_Pin                    GPIO_PIN_0
#define MX_ADC1_IN1_GPIO_Mode                   GPIO_MODE_ANALOG

/* DMA Configuration */

/* DMA ADC1 */
#define MX_ADC1_DMA_Instance                    DMA1_Channel1
#define MX_ADC1_DMA_RequestGeneratorInstance    None
#define MX_ADC1_DMA_Priority                    DMA_PRIORITY_LOW
#define MX_ADC1_DMA_MemDataAlignment            DMA_MDATAALIGN_HALFWORD
#define MX_ADC1_DMA_Mode                        DMA_CIRCULAR
#define MX_ADC1_DMA_SyncRequestNumber           1
#define MX_ADC1_DMA_Request                     DMA_REQUEST_ADC1
#define MX_ADC1_DMA_SyncPolarity                HAL_DMAMUX_SYNC_NO_EVENT
#define MX_ADC1_DMA_Direction                   DMA_PERIPH_TO_MEMORY
#define MX_ADC1_DMA_SignalID                    NONE
#define MX_ADC1_DMA_MemInc                      DMA_MINC_ENABLE
#define MX_ADC1_DMA_IpInstance
#define MX_ADC1_DMA_RequestNumber               1
#define MX_ADC1_DMA_EventEnable                 DISABLE
#define MX_ADC1_DMA_SyncEnable                  DISABLE
#define MX_ADC1_DMA_DMA_Handle
#define MX_ADC1_DMA_PeriphDataAlignment         DMA_PDATAALIGN_HALFWORD
#define MX_ADC1_DMA_Polarity                    HAL_DMAMUX_REQ_GEN_RISING
#define MX_ADC1_DMA_SyncSignalID                NONE
#define MX_ADC1_DMA_PeriphInc                   DMA_PINC_DISABLE

/*-------------------------------- ADC5       --------------------------------*/

#define MX_ADC5                                 1

/* GPIO Configuration */

/* Pin PA8 */
#define MX_ADC5_IN1_Pin                         PA8
#define MX_ADC5_IN1_GPIOx                       GPIOA
#define MX_ADC5_IN1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC5_IN1_GPIO_Pin                    GPIO_PIN_8
#define MX_ADC5_IN1_GPIO_Mode                   GPIO_MODE_ANALOG

/* DMA Configuration */

/* DMA ADC5 */
#define MX_ADC5_DMA_Instance                    DMA1_Channel2
#define MX_ADC5_DMA_RequestGeneratorInstance    None
#define MX_ADC5_DMA_Priority                    DMA_PRIORITY_LOW
#define MX_ADC5_DMA_MemDataAlignment            DMA_MDATAALIGN_HALFWORD
#define MX_ADC5_DMA_Mode                        DMA_CIRCULAR
#define MX_ADC5_DMA_SyncRequestNumber           1
#define MX_ADC5_DMA_Request                     DMA_REQUEST_ADC5
#define MX_ADC5_DMA_SyncPolarity                HAL_DMAMUX_SYNC_NO_EVENT
#define MX_ADC5_DMA_Direction                   DMA_PERIPH_TO_MEMORY
#define MX_ADC5_DMA_SignalID                    NONE
#define MX_ADC5_DMA_MemInc                      DMA_MINC_ENABLE
#define MX_ADC5_DMA_IpInstance
#define MX_ADC5_DMA_RequestNumber               1
#define MX_ADC5_DMA_EventEnable                 DISABLE
#define MX_ADC5_DMA_SyncEnable                  DISABLE
#define MX_ADC5_DMA_DMA_Handle
#define MX_ADC5_DMA_PeriphDataAlignment         DMA_PDATAALIGN_HALFWORD
#define MX_ADC5_DMA_Polarity                    HAL_DMAMUX_REQ_GEN_RISING
#define MX_ADC5_DMA_SyncSignalID                NONE
#define MX_ADC5_DMA_PeriphInc                   DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC ADC5_IRQn */
#define MX_ADC5_IRQn_interruptPremptionPriority 0
#define MX_ADC5_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_ADC5_IRQn_Subriority                 0

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA1_Channel6_IRQn */
#define MX_DMA1_Channel6_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel6_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA1_Channel6_IRQn_Subriority        0

/* NVIC DMA1_Channel3_IRQn */
#define MX_DMA1_Channel3_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel3_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA1_Channel3_IRQn_Subriority        0

/* NVIC DMA1_Channel1_IRQn */
#define MX_DMA1_Channel1_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel1_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA1_Channel1_IRQn_Subriority        0

/* NVIC DMA2_Channel2_IRQn */
#define MX_DMA2_Channel2_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Channel2_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA2_Channel2_IRQn_Subriority        0

/* NVIC DMA1_Channel2_IRQn */
#define MX_DMA1_Channel2_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel2_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA1_Channel2_IRQn_Subriority        0

/* NVIC DMA1_Channel5_IRQn */
#define MX_DMA1_Channel5_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel5_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA1_Channel5_IRQn_Subriority        0

/* NVIC DMA1_Channel8_IRQn */
#define MX_DMA1_Channel8_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel8_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA1_Channel8_IRQn_Subriority        0

/* NVIC DMA1_Channel4_IRQn */
#define MX_DMA1_Channel4_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel4_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA1_Channel4_IRQn_Subriority        0

/* NVIC DMA2_Channel1_IRQn */
#define MX_DMA2_Channel1_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Channel1_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA2_Channel1_IRQn_Subriority        0

/*-------------------------------- FMAC       --------------------------------*/

#define MX_FMAC                                 1

/* GPIO Configuration */

/* DMA Configuration */

/* DMA FMAC_READ */
#define MX_FMAC_READ_DMA_Instance               DMA2_Channel1
#define MX_FMAC_READ_DMA_RequestGeneratorInstance None
#define MX_FMAC_READ_DMA_Priority               DMA_PRIORITY_LOW
#define MX_FMAC_READ_DMA_MemDataAlignment       DMA_MDATAALIGN_HALFWORD
#define MX_FMAC_READ_DMA_Mode                   DMA_NORMAL
#define MX_FMAC_READ_DMA_SyncRequestNumber      1
#define MX_FMAC_READ_DMA_Request                DMA_REQUEST_FMAC_READ
#define MX_FMAC_READ_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_FMAC_READ_DMA_Direction              DMA_PERIPH_TO_MEMORY
#define MX_FMAC_READ_DMA_SignalID               NONE
#define MX_FMAC_READ_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_FMAC_READ_DMA_IpInstance
#define MX_FMAC_READ_DMA_RequestNumber          1
#define MX_FMAC_READ_DMA_EventEnable            DISABLE
#define MX_FMAC_READ_DMA_SyncEnable             DISABLE
#define MX_FMAC_READ_DMA_DMA_Handle
#define MX_FMAC_READ_DMA_PeriphDataAlignment    DMA_PDATAALIGN_WORD
#define MX_FMAC_READ_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_FMAC_READ_DMA_SyncSignalID           NONE
#define MX_FMAC_READ_DMA_PeriphInc              DMA_PINC_DISABLE

/* DMA FMAC_PRELOAD */
#define MX_FMAC_PRELOAD_DMA_Instance            DMA1_Channel8
#define MX_FMAC_PRELOAD_DMA_RequestGeneratorInstance None
#define MX_FMAC_PRELOAD_DMA_Priority            DMA_PRIORITY_LOW
#define MX_FMAC_PRELOAD_DMA_MemDataAlignment    DMA_MDATAALIGN_WORD
#define MX_FMAC_PRELOAD_DMA_Mode                DMA_NORMAL
#define MX_FMAC_PRELOAD_DMA_SyncRequestNumber   1
#define MX_FMAC_PRELOAD_DMA_Request             DMA_REQUEST_MEM2MEM
#define MX_FMAC_PRELOAD_DMA_SyncPolarity        HAL_DMAMUX_SYNC_NO_EVENT
#define MX_FMAC_PRELOAD_DMA_Direction           DMA_MEMORY_TO_MEMORY
#define MX_FMAC_PRELOAD_DMA_SignalID            NONE
#define MX_FMAC_PRELOAD_DMA_MemInc              DMA_MINC_DISABLE
#define MX_FMAC_PRELOAD_DMA_IpInstance
#define MX_FMAC_PRELOAD_DMA_RequestNumber       1
#define MX_FMAC_PRELOAD_DMA_EventEnable         DISABLE
#define MX_FMAC_PRELOAD_DMA_SyncEnable          DISABLE
#define MX_FMAC_PRELOAD_DMA_DMA_Handle
#define MX_FMAC_PRELOAD_DMA_PeriphDataAlignment DMA_PDATAALIGN_HALFWORD
#define MX_FMAC_PRELOAD_DMA_Polarity            HAL_DMAMUX_REQ_GEN_RISING
#define MX_FMAC_PRELOAD_DMA_SyncSignalID        NONE
#define MX_FMAC_PRELOAD_DMA_PeriphInc           DMA_PINC_ENABLE

/* DMA FMAC_WRITE */
#define MX_FMAC_WRITE_DMA_Instance              DMA2_Channel2
#define MX_FMAC_WRITE_DMA_RequestGeneratorInstance None
#define MX_FMAC_WRITE_DMA_Priority              DMA_PRIORITY_LOW
#define MX_FMAC_WRITE_DMA_MemDataAlignment      DMA_MDATAALIGN_HALFWORD
#define MX_FMAC_WRITE_DMA_Mode                  DMA_NORMAL
#define MX_FMAC_WRITE_DMA_SyncRequestNumber     1
#define MX_FMAC_WRITE_DMA_Request               DMA_REQUEST_FMAC_WRITE
#define MX_FMAC_WRITE_DMA_SyncPolarity          HAL_DMAMUX_SYNC_NO_EVENT
#define MX_FMAC_WRITE_DMA_Direction             DMA_MEMORY_TO_PERIPH
#define MX_FMAC_WRITE_DMA_SignalID              NONE
#define MX_FMAC_WRITE_DMA_MemInc                DMA_MINC_ENABLE
#define MX_FMAC_WRITE_DMA_IpInstance
#define MX_FMAC_WRITE_DMA_RequestNumber         1
#define MX_FMAC_WRITE_DMA_EventEnable           DISABLE
#define MX_FMAC_WRITE_DMA_SyncEnable            DISABLE
#define MX_FMAC_WRITE_DMA_DMA_Handle
#define MX_FMAC_WRITE_DMA_PeriphDataAlignment   DMA_PDATAALIGN_WORD
#define MX_FMAC_WRITE_DMA_Polarity              HAL_DMAMUX_REQ_GEN_RISING
#define MX_FMAC_WRITE_DMA_SyncSignalID          NONE
#define MX_FMAC_WRITE_DMA_PeriphInc             DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC FMAC_IRQn */
#define MX_FMAC_IRQn_interruptPremptionPriority 0
#define MX_FMAC_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_FMAC_IRQn_Subriority                 0

/*-------------------------------- FMC        --------------------------------*/

#define MX_FMC                                  1

/* GPIO Configuration */

/* Pin PD15 */
#define MX_FMC_D1_Pin                           PD15
#define MX_FMC_D1_GPIOx                         GPIOD
#define MX_FMC_D1_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D1_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_HIGH
#define MX_FMC_D1_GPIO_Pin                      GPIO_PIN_15
#define MX_FMC_D1_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D1_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD0 */
#define MX_FMC_D2_Pin                           PD0
#define MX_FMC_D2_GPIOx                         GPIOD
#define MX_FMC_D2_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D2_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_HIGH
#define MX_FMC_D2_GPIO_Pin                      GPIO_PIN_0
#define MX_FMC_D2_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D2_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD12 */
#define MX_FMC_ALE_Pin                          PD12
#define MX_FMC_ALE_GPIOx                        GPIOD
#define MX_FMC_ALE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_ALE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_HIGH
#define MX_FMC_ALE_GPIO_Pin                     GPIO_PIN_12
#define MX_FMC_ALE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD1 */
#define MX_FMC_D3_Pin                           PD1
#define MX_FMC_D3_GPIOx                         GPIOD
#define MX_FMC_D3_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D3_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_HIGH
#define MX_FMC_D3_GPIO_Pin                      GPIO_PIN_1
#define MX_FMC_D3_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D3_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD6 */
#define MX_FMC_NWAIT_Pin                        PD6
#define MX_FMC_NWAIT_GPIOx                      GPIOD
#define MX_FMC_NWAIT_GPIO_PuPd                  GPIO_PULLUP
#define MX_FMC_NWAIT_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_HIGH
#define MX_FMC_NWAIT_GPIO_Pin                   GPIO_PIN_6
#define MX_FMC_NWAIT_GPIO_AF                    GPIO_AF12_FMC
#define MX_FMC_NWAIT_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PE7 */
#define MX_FMC_D4_Pin                           PE7
#define MX_FMC_D4_GPIOx                         GPIOE
#define MX_FMC_D4_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D4_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_HIGH
#define MX_FMC_D4_GPIO_Pin                      GPIO_PIN_7
#define MX_FMC_D4_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D4_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PE8 */
#define MX_FMC_D5_Pin                           PE8
#define MX_FMC_D5_GPIOx                         GPIOE
#define MX_FMC_D5_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D5_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_HIGH
#define MX_FMC_D5_GPIO_Pin                      GPIO_PIN_8
#define MX_FMC_D5_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D5_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PE9 */
#define MX_FMC_D6_Pin                           PE9
#define MX_FMC_D6_GPIOx                         GPIOE
#define MX_FMC_D6_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D6_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_HIGH
#define MX_FMC_D6_GPIO_Pin                      GPIO_PIN_9
#define MX_FMC_D6_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D6_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PE10 */
#define MX_FMC_D7_Pin                           PE10
#define MX_FMC_D7_GPIOx                         GPIOE
#define MX_FMC_D7_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D7_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_HIGH
#define MX_FMC_D7_GPIO_Pin                      GPIO_PIN_10
#define MX_FMC_D7_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D7_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD11 */
#define MX_FMC_CLE_Pin                          PD11
#define MX_FMC_CLE_GPIOx                        GPIOD
#define MX_FMC_CLE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_CLE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_HIGH
#define MX_FMC_CLE_GPIO_Pin                     GPIO_PIN_11
#define MX_FMC_CLE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD5 */
#define MX_FMC_NWE_Pin                          PD5
#define MX_FMC_NWE_GPIOx                        GPIOD
#define MX_FMC_NWE_GPIO_PuPd                    GPIO_PULLUP
#define MX_FMC_NWE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_HIGH
#define MX_FMC_NWE_GPIO_Pin                     GPIO_PIN_5
#define MX_FMC_NWE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_NWE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD4 */
#define MX_FMC_NOE_Pin                          PD4
#define MX_FMC_NOE_GPIOx                        GPIOD
#define MX_FMC_NOE_GPIO_PuPd                    GPIO_PULLUP
#define MX_FMC_NOE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_HIGH
#define MX_FMC_NOE_GPIO_Pin                     GPIO_PIN_4
#define MX_FMC_NOE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_NOE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD7 */
#define MX_FMC_NCE_Pin                          PD7
#define MX_FMC_NCE_GPIOx                        GPIOD
#define MX_FMC_NCE_GPIO_PuPd                    GPIO_PULLUP
#define MX_FMC_NCE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_HIGH
#define MX_FMC_NCE_GPIO_Pin                     GPIO_PIN_7
#define MX_FMC_NCE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_NCE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD14 */
#define MX_FMC_D0_Pin                           PD14
#define MX_FMC_D0_GPIOx                         GPIOD
#define MX_FMC_D0_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D0_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_HIGH
#define MX_FMC_D0_GPIO_Pin                      GPIO_PIN_14
#define MX_FMC_D0_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D0_GPIO_Mode                     GPIO_MODE_AF_PP

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PA15 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SCL_Pin                         PA15
#define MX_I2C1_SCL_GPIOx                       GPIOA
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_15
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB7 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SDA_Pin                         PB7
#define MX_I2C1_SDA_GPIOx                       GPIOB
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_7
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C1_SDA_GPIO_FM7                    __NULL
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- OPAMP4     --------------------------------*/

#define MX_OPAMP4                               1

/* GPIO Configuration */

/* Pin PB11 */
#define MX_OPAMP4_VINP_Pin                      PB11
#define MX_OPAMP4_VINP_GPIOx                    GPIOB
#define MX_OPAMP4_VINP_GPIO_PuPd                GPIO_NOPULL
#define MX_OPAMP4_VINP_GPIO_Pin                 GPIO_PIN_11
#define MX_OPAMP4_VINP_GPIO_Mode                GPIO_MODE_ANALOG

/*-------------------------------- OPAMP5     --------------------------------*/

#define MX_OPAMP5                               1

/* GPIO Configuration */

/* Pin PC3 */
#define MX_OPAMP5_VINP_Pin                      PC3
#define MX_OPAMP5_VINP_GPIOx                    GPIOC
#define MX_OPAMP5_VINP_GPIO_PuPd                GPIO_NOPULL
#define MX_OPAMP5_VINP_GPIO_Pin                 GPIO_PIN_3
#define MX_OPAMP5_VINP_GPIO_Mode                GPIO_MODE_ANALOG

/*-------------------------------- QUADSPI1   --------------------------------*/

#define MX_QUADSPI1                             1

/* GPIO Configuration */

/* Pin PF10 */
#define MX_QUADSPI1_CLK_GPIO_Speed              GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI1_CLK_Pin                     PF10
#define MX_QUADSPI1_CLK_GPIOx                   GPIOF
#define MX_QUADSPI1_CLK_GPIO_PuPd               GPIO_NOPULL
#define MX_QUADSPI1_CLK_GPIO_Pin                GPIO_PIN_10
#define MX_QUADSPI1_CLK_GPIO_AF                 GPIO_AF10_QUADSPI
#define MX_QUADSPI1_CLK_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PE11 */
#define MX_QUADSPI1_BK1_NCS_GPIO_Speed          GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI1_BK1_NCS_Pin                 PE11
#define MX_QUADSPI1_BK1_NCS_GPIOx               GPIOE
#define MX_QUADSPI1_BK1_NCS_GPIO_PuPd           GPIO_NOPULL
#define MX_QUADSPI1_BK1_NCS_GPIO_Pin            GPIO_PIN_11
#define MX_QUADSPI1_BK1_NCS_GPIO_AF             GPIO_AF10_QUADSPI
#define MX_QUADSPI1_BK1_NCS_GPIO_Mode           GPIO_MODE_AF_PP

/* Pin PE15 */
#define MX_QUADSPI1_BK1_IO3_GPIO_Speed          GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI1_BK1_IO3_Pin                 PE15
#define MX_QUADSPI1_BK1_IO3_GPIOx               GPIOE
#define MX_QUADSPI1_BK1_IO3_GPIO_PuPd           GPIO_NOPULL
#define MX_QUADSPI1_BK1_IO3_GPIO_Pin            GPIO_PIN_15
#define MX_QUADSPI1_BK1_IO3_GPIO_AF             GPIO_AF10_QUADSPI
#define MX_QUADSPI1_BK1_IO3_GPIO_Mode           GPIO_MODE_AF_PP

/* Pin PE14 */
#define MX_QUADSPI1_BK1_IO2_GPIO_Speed          GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI1_BK1_IO2_Pin                 PE14
#define MX_QUADSPI1_BK1_IO2_GPIOx               GPIOE
#define MX_QUADSPI1_BK1_IO2_GPIO_PuPd           GPIO_NOPULL
#define MX_QUADSPI1_BK1_IO2_GPIO_Pin            GPIO_PIN_14
#define MX_QUADSPI1_BK1_IO2_GPIO_AF             GPIO_AF10_QUADSPI
#define MX_QUADSPI1_BK1_IO2_GPIO_Mode           GPIO_MODE_AF_PP

/* Pin PF9 */
#define MX_QUADSPI1_BK1_IO1_GPIO_Speed          GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI1_BK1_IO1_Pin                 PF9
#define MX_QUADSPI1_BK1_IO1_GPIOx               GPIOF
#define MX_QUADSPI1_BK1_IO1_GPIO_PuPd           GPIO_NOPULL
#define MX_QUADSPI1_BK1_IO1_GPIO_Pin            GPIO_PIN_9
#define MX_QUADSPI1_BK1_IO1_GPIO_AF             GPIO_AF10_QUADSPI
#define MX_QUADSPI1_BK1_IO1_GPIO_Mode           GPIO_MODE_AF_PP

/* Pin PE12 */
#define MX_QUADSPI1_BK1_IO0_GPIO_Speed          GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI1_BK1_IO0_Pin                 PE12
#define MX_QUADSPI1_BK1_IO0_GPIOx               GPIOE
#define MX_QUADSPI1_BK1_IO0_GPIO_PuPd           GPIO_NOPULL
#define MX_QUADSPI1_BK1_IO0_GPIO_Pin            GPIO_PIN_12
#define MX_QUADSPI1_BK1_IO0_GPIO_AF             GPIO_AF10_QUADSPI
#define MX_QUADSPI1_BK1_IO0_GPIO_Mode           GPIO_MODE_AF_PP

/*-------------------------------- RTC        --------------------------------*/

#define MX_RTC                                  1

/* GPIO Configuration */

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS_SWDIO_Pin                   PA13

/* Pin PA14 */
#define MX_SYS_JTCK_SWCLK_Pin                   PA14

/*-------------------------------- TIM1       --------------------------------*/

#define MX_TIM1                                 1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM1_UP_TIM16_IRQn */
#define MX_TIM1_UP_TIM16_IRQn_interruptPremptionPriority 0
#define MX_TIM1_UP_TIM16_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_TIM1_UP_TIM16_IRQn_Subriority        0

/*-------------------------------- TIM2       --------------------------------*/

#define MX_TIM2                                 1

/* GPIO Configuration */

/* Pin PA9 */
#define MX_S_TIM2_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM2_CH3_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM2_CH3_Pin                       PA9
#define MX_S_TIM2_CH3_GPIOx                     GPIOA
#define MX_S_TIM2_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM2_CH3_GPIO_Pin                  GPIO_PIN_9
#define MX_S_TIM2_CH3_GPIO_AF                   GPIO_AF10_TIM2

/*-------------------------------- TIM3       --------------------------------*/

#define MX_TIM3                                 1

/* GPIO Configuration */

/*-------------------------------- TIM4       --------------------------------*/

#define MX_TIM4                                 1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM4_IRQn */
#define MX_TIM4_IRQn_interruptPremptionPriority 0
#define MX_TIM4_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_TIM4_IRQn_Subriority                 0

/*-------------------------------- TIM8       --------------------------------*/

#define MX_TIM8                                 1

/* GPIO Configuration */

/*-------------------------------- USART1     --------------------------------*/

#define MX_USART1                               1

#define MX_USART1_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PC4 */
#define MX_USART1_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART1_TX_Pin                        PC4
#define MX_USART1_TX_GPIOx                      GPIOC
#define MX_USART1_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_TX_GPIO_Pin                   GPIO_PIN_4
#define MX_USART1_TX_GPIO_AF                    GPIO_AF7_USART1

/* Pin PC5 */
#define MX_USART1_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART1_RX_Pin                        PC5
#define MX_USART1_RX_GPIOx                      GPIOC
#define MX_USART1_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_RX_GPIO_Pin                   GPIO_PIN_5
#define MX_USART1_RX_GPIO_AF                    GPIO_AF7_USART1

/* DMA Configuration */

/* DMA USART1_TX */
#define MX_USART1_TX_DMA_Instance               DMA1_Channel6
#define MX_USART1_TX_DMA_RequestGeneratorInstance None
#define MX_USART1_TX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART1_TX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART1_TX_DMA_Mode                   DMA_NORMAL
#define MX_USART1_TX_DMA_SyncRequestNumber      1
#define MX_USART1_TX_DMA_Request                DMA_REQUEST_USART1_TX
#define MX_USART1_TX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART1_TX_DMA_Direction              DMA_MEMORY_TO_PERIPH
#define MX_USART1_TX_DMA_SignalID               NONE
#define MX_USART1_TX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART1_TX_DMA_IpInstance
#define MX_USART1_TX_DMA_RequestNumber          1
#define MX_USART1_TX_DMA_EventEnable            DISABLE
#define MX_USART1_TX_DMA_SyncEnable             DISABLE
#define MX_USART1_TX_DMA_DMA_Handle
#define MX_USART1_TX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART1_TX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART1_TX_DMA_SyncSignalID           NONE
#define MX_USART1_TX_DMA_PeriphInc              DMA_PINC_DISABLE

/* DMA USART1_RX */
#define MX_USART1_RX_DMA_Instance               DMA1_Channel5
#define MX_USART1_RX_DMA_RequestGeneratorInstance None
#define MX_USART1_RX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART1_RX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART1_RX_DMA_Mode                   DMA_NORMAL
#define MX_USART1_RX_DMA_SyncRequestNumber      1
#define MX_USART1_RX_DMA_Request                DMA_REQUEST_USART1_RX
#define MX_USART1_RX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART1_RX_DMA_Direction              DMA_PERIPH_TO_MEMORY
#define MX_USART1_RX_DMA_SignalID               NONE
#define MX_USART1_RX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART1_RX_DMA_IpInstance
#define MX_USART1_RX_DMA_RequestNumber          1
#define MX_USART1_RX_DMA_EventEnable            DISABLE
#define MX_USART1_RX_DMA_SyncEnable             DISABLE
#define MX_USART1_RX_DMA_DMA_Handle
#define MX_USART1_RX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART1_RX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART1_RX_DMA_SyncSignalID           NONE
#define MX_USART1_RX_DMA_PeriphInc              DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC USART1_IRQn */
#define MX_USART1_IRQn_interruptPremptionPriority 2
#define MX_USART1_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USART1_IRQn_Subriority               0

/*-------------------------------- USART3     --------------------------------*/

#define MX_USART3                               1

#define MX_USART3_VM                            VM_ASYNC
#define MX_USART3_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PD8 */
#define MX_USART3_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART3_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART3_TX_Pin                        PD8
#define MX_USART3_TX_GPIOx                      GPIOD
#define MX_USART3_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART3_TX_GPIO_Pin                   GPIO_PIN_8
#define MX_USART3_TX_GPIO_AF                    GPIO_AF7_USART3

/* Pin PD9 */
#define MX_USART3_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART3_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART3_RX_Pin                        PD9
#define MX_USART3_RX_GPIOx                      GPIOD
#define MX_USART3_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART3_RX_GPIO_Pin                   GPIO_PIN_9
#define MX_USART3_RX_GPIO_AF                    GPIO_AF7_USART3

/* Pin PB14 */
#define MX_USART3_DE_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART3_DE_Pin                        PB14
#define MX_USART3_DE_GPIOx                      GPIOB
#define MX_USART3_DE_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART3_DE_GPIO_Pin                   GPIO_PIN_14
#define MX_USART3_DE_GPIO_AF                    GPIO_AF7_USART3
#define MX_USART3_DE_GPIO_Mode                  GPIO_MODE_AF_PP

/* DMA Configuration */

/* DMA USART3_TX */
#define MX_USART3_TX_DMA_Instance               DMA1_Channel4
#define MX_USART3_TX_DMA_RequestGeneratorInstance None
#define MX_USART3_TX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART3_TX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART3_TX_DMA_Mode                   DMA_NORMAL
#define MX_USART3_TX_DMA_SyncRequestNumber      1
#define MX_USART3_TX_DMA_Request                DMA_REQUEST_USART3_TX
#define MX_USART3_TX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART3_TX_DMA_Direction              DMA_MEMORY_TO_PERIPH
#define MX_USART3_TX_DMA_SignalID               NONE
#define MX_USART3_TX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART3_TX_DMA_IpInstance
#define MX_USART3_TX_DMA_RequestNumber          1
#define MX_USART3_TX_DMA_EventEnable            DISABLE
#define MX_USART3_TX_DMA_SyncEnable             DISABLE
#define MX_USART3_TX_DMA_DMA_Handle
#define MX_USART3_TX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART3_TX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART3_TX_DMA_SyncSignalID           NONE
#define MX_USART3_TX_DMA_PeriphInc              DMA_PINC_DISABLE

/* DMA USART3_RX */
#define MX_USART3_RX_DMA_Instance               DMA1_Channel3
#define MX_USART3_RX_DMA_RequestGeneratorInstance None
#define MX_USART3_RX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART3_RX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART3_RX_DMA_Mode                   DMA_CIRCULAR
#define MX_USART3_RX_DMA_SyncRequestNumber      1
#define MX_USART3_RX_DMA_Request                DMA_REQUEST_USART3_RX
#define MX_USART3_RX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART3_RX_DMA_Direction              DMA_PERIPH_TO_MEMORY
#define MX_USART3_RX_DMA_SignalID               NONE
#define MX_USART3_RX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART3_RX_DMA_IpInstance
#define MX_USART3_RX_DMA_RequestNumber          1
#define MX_USART3_RX_DMA_EventEnable            DISABLE
#define MX_USART3_RX_DMA_SyncEnable             DISABLE
#define MX_USART3_RX_DMA_DMA_Handle
#define MX_USART3_RX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART3_RX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART3_RX_DMA_SyncSignalID           NONE
#define MX_USART3_RX_DMA_PeriphInc              DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC USART3_IRQn */
#define MX_USART3_IRQn_interruptPremptionPriority 0
#define MX_USART3_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USART3_IRQn_Subriority               0

/*-------------------------------- USB        --------------------------------*/

#define MX_USB                                  1

/* GPIO Configuration */

/* Pin PA11 */
#define MX_USB_DM_Pin                           PA11

/* Pin PA12 */
#define MX_USB_DP_Pin                           PA12

/* NVIC Configuration */

/* NVIC USB_HP_IRQn */
#define MX_USB_HP_IRQn_interruptPremptionPriority 0
#define MX_USB_HP_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USB_HP_IRQn_Subriority               0

/* NVIC USB_LP_IRQn */
#define MX_USB_LP_IRQn_interruptPremptionPriority 0
#define MX_USB_LP_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USB_LP_IRQn_Subriority               0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PE6 */
#define MX_PE6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE6_Pin                              PE6
#define MX_PE6_GPIOx                            GPIOE
#define MX_PE6_PinState                         GPIO_PIN_RESET
#define MX_PE6_GPIO_PuPd                        GPIO_NOPULL
#define MX_SenV                                 PE6
#define MX_PE6_GPIO_Pin                         GPIO_PIN_6
#define MX_PE6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB3 */
#define MX_PB3_GPIO_Speed                       GPIO_SPEED_FREQ_MEDIUM
#define MX_PB3_Pin                              PB3
#define MX_PB3_GPIOx                            GPIOB
#define MX_PB3_PinState                         GPIO_PIN_RESET
#define MX_PB3_GPIO_PuPd                        GPIO_NOPULL
#define MX_MagGainZ                             PB3
#define MX_PB3_GPIO_Pin                         GPIO_PIN_3
#define MX_PB3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE5 */
#define MX_PE5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE5_Pin                              PE5
#define MX_PE5_GPIOx                            GPIOE
#define MX_PE5_PinState                         GPIO_PIN_RESET
#define MX_PE5_GPIO_PuPd                        GPIO_NOPULL
#define MX_MagV                                 PE5
#define MX_PE5_GPIO_Pin                         GPIO_PIN_5
#define MX_PE5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB2 */
#define MX_PB2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB2_Pin                              PB2
#define MX_PB2_GPIOx                            GPIOB
#define MX_PB2_PinState                         GPIO_PIN_RESET
#define MX_PB2_GPIO_PuPd                        GPIO_NOPULL
#define MX_PULSE                                PB2
#define MX_PB2_GPIO_Pin                         GPIO_PIN_2
#define MX_PB2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA4 */
#define MX_PA4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA4_Pin                              PA4
#define MX_PA4_GPIOx                            GPIOA
#define MX_PA4_PinState                         GPIO_PIN_RESET
#define MX_PA4_GPIO_PuPd                        GPIO_PULLUP
#define MX_BAT2SW                               PA4
#define MX_PA4_GPIO_Pin                         GPIO_PIN_4
#define MX_PA4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB5 */
#define MX_PB5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB5_Pin                              PB5
#define MX_PB5_GPIOx                            GPIOB
#define MX_PB5_PinState                         GPIO_PIN_SET
#define MX_PB5_GPIO_PuPd                        GPIO_NOPULL
#define MX_LED_R                                PB5
#define MX_PB5_GPIO_Pin                         GPIO_PIN_5
#define MX_PB5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA3 */
#define MX_PA3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA3_Pin                              PA3
#define MX_PA3_GPIOx                            GPIOA
#define MX_PA3_PinState                         GPIO_PIN_RESET
#define MX_PA3_GPIO_PuPd                        GPIO_PULLUP
#define MX_BAT1SW                               PA3
#define MX_PA3_GPIO_Pin                         GPIO_PIN_3
#define MX_PA3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA6 */
#define MX_PA6_Pin                              PA6
#define MX_PA6_GPIOx                            GPIOA
#define MX_PA6_GPIO_PuPd                        GPIO_PULLDOWN
#define MX_SPI1_MISO                            PA6
#define MX_PA6_GPIO_Pin                         GPIO_PIN_6
#define MX_PA6_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PA5 */
#define MX_PA5_GPIO_Speed                       GPIO_SPEED_FREQ_MEDIUM
#define MX_PA5_Pin                              PA5
#define MX_PA5_GPIOx                            GPIOA
#define MX_PA5_PinState                         GPIO_PIN_RESET
#define MX_PA5_GPIO_PuPd                        GPIO_PULLDOWN
#define MX_SPI1_SCK                             PA5
#define MX_PA5_GPIO_Pin                         GPIO_PIN_5
#define MX_PA5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB6 */
#define MX_PB6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB6_GPIO_FM6                         __NULL
#define MX_PB6_Pin                              PB6
#define MX_PB6_GPIOx                            GPIOB
#define MX_PB6_PinState                         GPIO_PIN_SET
#define MX_PB6_GPIO_PuPd                        GPIO_NOPULL
#define MX_LED_G                                PB6
#define MX_PB6_GPIO_Pin                         GPIO_PIN_6
#define MX_PB6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA7 */
#define MX_PA7_GPIO_Speed                       GPIO_SPEED_FREQ_MEDIUM
#define MX_PA7_Pin                              PA7
#define MX_PA7_GPIOx                            GPIOA
#define MX_PA7_PinState                         GPIO_PIN_RESET
#define MX_PA7_GPIO_PuPd                        GPIO_PULLDOWN
#define MX_SPI1_MOSI                            PA7
#define MX_PA7_GPIO_Pin                         GPIO_PIN_7
#define MX_PA7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC12 */
#define MX_PC12_GPIO_Speed                      GPIO_SPEED_FREQ_MEDIUM
#define MX_PC12_Pin                             PC12
#define MX_PC12_GPIOx                           GPIOC
#define MX_PC12_PinState                        GPIO_PIN_RESET
#define MX_PC12_GPIO_PuPd                       GPIO_NOPULL
#define MX_MagGainY                             PC12
#define MX_PC12_GPIO_Pin                        GPIO_PIN_12
#define MX_PC12_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PG10-NRST */
#define MX_PG10_NRST_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_PG10_NRST_Pin                        PG10_NRST
#define MX_PG10_NRST_GPIOx                      GPIOG
#define MX_PG10_NRST_PinState                   GPIO_PIN_RESET
#define MX_PG10_NRST_GPIO_PuPd                  GPIO_NOPULL
#define MX_ARM_RESET                            PG10_NRST
#define MX_PG10_NRST_GPIO_Pin                   GPIO_PIN_10
#define MX_PG10_NRST_GPIO_ModeDefaultOutputPP   GPIO_MODE_OUTPUT_PP

/* Pin PA10 */
#define MX_PA10_Pin                             PA10
#define MX_PA10_GPIOx                           GPIOA
#define MX_PA10_GPIO_PuPd                       GPIO_PULLDOWN
#define MX_bUSBPlug                             PA10
#define MX_PA10_GPIO_Pin                        GPIO_PIN_10
#define MX_PA10_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PC10 */
#define MX_PC10_GPIO_Speed                      GPIO_SPEED_FREQ_MEDIUM
#define MX_PC10_Pin                             PC10
#define MX_PC10_GPIOx                           GPIOC
#define MX_PC10_PinState                        GPIO_PIN_RESET
#define MX_PC10_GPIO_PuPd                       GPIO_NOPULL
#define MX_MagGainX                             PC10
#define MX_PC10_GPIO_Pin                        GPIO_PIN_10
#define MX_PC10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PC0 */
#define MX_PC0_GPIO_Speed                       GPIO_SPEED_FREQ_MEDIUM
#define MX_PC0_Pin                              PC0
#define MX_PC0_GPIOx                            GPIOC
#define MX_PC0_PinState                         GPIO_PIN_SET
#define MX_PC0_GPIO_PuPd                        GPIO_PULLUP
#define MX_ADC1_CS                              PC0
#define MX_PC0_GPIO_Pin                         GPIO_PIN_0
#define MX_PC0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE4 */
#define MX_PE4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE4_Pin                              PE4
#define MX_PE4_GPIOx                            GPIOE
#define MX_PE4_PinState                         GPIO_PIN_RESET
#define MX_PE4_GPIO_PuPd                        GPIO_NOPULL
#define MX_Shk                                  PE4
#define MX_PE4_GPIO_Pin                         GPIO_PIN_4
#define MX_PE4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC2 */
#define MX_PC2_GPIO_Speed                       GPIO_SPEED_FREQ_MEDIUM
#define MX_PC2_Pin                              PC2
#define MX_PC2_GPIOx                            GPIOC
#define MX_PC2_PinState                         GPIO_PIN_SET
#define MX_PC2_GPIO_PuPd                        GPIO_PULLUP
#define MX_ADC3_CS                              PC2
#define MX_PC2_GPIO_Pin                         GPIO_PIN_2
#define MX_PC2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB1 */
#define MX_PB1_Pin                              PB1
#define MX_PB1_GPIOx                            GPIOB
#define MX_PB1_GPIO_PuPd                        GPIO_NOPULL
#define MX_GR                                   PB1
#define MX_PB1_GPIO_Pin                         GPIO_PIN_1
#define MX_PB1_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PC1 */
#define MX_PC1_GPIO_Speed                       GPIO_SPEED_FREQ_MEDIUM
#define MX_PC1_Pin                              PC1
#define MX_PC1_GPIOx                            GPIOC
#define MX_PC1_PinState                         GPIO_PIN_SET
#define MX_PC1_GPIO_PuPd                        GPIO_PULLUP
#define MX_ADC2_CS                              PC1
#define MX_PC1_GPIO_Pin                         GPIO_PIN_1
#define MX_PC1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB0 */
#define MX_PB0_Pin                              PB0
#define MX_PB0_GPIOx                            GPIOB
#define MX_PB0_GPIO_PuPd                        GPIO_NOPULL
#define MX_FLOW                                 PB0
#define MX_PB0_GPIO_Pin                         GPIO_PIN_0
#define MX_PB0_GPIO_Mode                        GPIO_MODE_INPUT

#endif  /* __MX_DEVICE_H */

