/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
 * Generated on: 27-Apr-2022 16:00:12
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 II 型，二阶节
 * 节数     : 2
 * 稳定     : 是
 * 线性相位   : 否
 * 算术     : fixed
 * 分子     : s16,13 -> [-4 4)
 * 分母     : s16,14 -> [-2 2)
 * 定标值    : s16,20 -> [-3.125000e-02 3.125000e-02)
 * 输入     : s16,13 -> [-4 4)
 * 节输入    : s16,14 -> [-2 2)
 * 节输出    : s16,10 -> [-32 32)
 * 输出     : s16,10 -> [-32 32)
 * 状态     : s16,15 -> [-1 1)
 * 分子乘积   : s32,28 -> [-8 8)
 * 分母乘积   : s32,29 -> [-4 4)
 * 分子累加   : s40,28 -> [-2048 2048)
 * 分母累加   : s40,29 -> [-1024 1024)
 * 取整模式   : convergent
 * 溢出模式   : wrap
 * 求和前转换  : true
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\MATLAB\R2021b\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 5
const int NL[MWSPT_NSEC] = { 1,3,1,3,1 };
const int16_T RawData_IIR_B[MWSPT_NSEC][3] = {
  {
      213,      0,      0 
  },
  {
     8192,  16384,   8192 
  },
  {
      183,      0,      0 
  },
  {
     8192,  16384,   8192 
  },
  {
     8192,      0,      0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1 };
const int16_T RawData_IIR_A[MWSPT_NSEC][3] = {
  {
     8192,      0,      0 
  },
  {
     8192, -13659,   6318 
  },
  {
     8192,      0,      0 
  },
  {
     8192, -11757,   4298 
  },
  {
     8192,      0,      0 
  }
};
